name: StoryRubini
version: '1.1'
main: xyz.binarycodee.storyrpg.StoryRubini
api-version: '1.20'
authors: [BinaryCodee]
commands:
  daily:
    aliases:
      - giornaliero
      - premio
      - reward
      - rewards
      - premiodaily
      - dailypremio
  rubini:
    aliases:
      - gemme
      - gems
      - rubies
      - ruby
      - rubino